#!/bin/dash

# colors
black=#32302f
darkblack=#1d2021
grey=#3c3836
green=#a9b665
white=#d4be98
blue=#7daea3
darkblue=#45707a
red=#ea6962
darkred=#c14a4a
magenta=#d3869b
yellow=#e78a4e
darkyellow=#d79921
